# v005: same as v004

# Changelog
# - consider 'equivalent_up_to_global_phase' as correct for QCEC check


commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/morphq_w_oracles.jinja
      output_folder: program_bank/v005/
      max_n_qubits: 32
      max_n_gates: 10
      max_n_programs: 100000
      perform_execution: False