# v007: support more strategies for circuit generation

# Changelog
# - add support for using circuit fragments

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_oracles.jinja
      output_folder: program_bank/v007/
      seed_qasm_folder: data/circuit_fragments_qasm
      circuit_generation_strategy: "circuit_fragments"
      max_n_programs: 100000
      perform_execution: False