# v009: support multiple circuit stitching strategies

# Changelog
# - add support for
#     - Sequential Knitting
#     - Parallel Knitting
#     - Interleaved Knitting
#     - Unitary Knitting
# - select one of the above at random

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_oracles.jinja
      output_folder: program_bank/v009/
      seed_program_folder: data/circuit_fragments
      circuit_generation_strategy: "spiu_knitting"
      max_n_programs: 10000
      perform_execution: False