# v012: LLM Generator

# Changelog
# - add generator that uses LLM and documentation

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_oracles_any_circuit_var.jinja
      output_folder: program_bank/v012/
      circuit_generation_strategy: "llm_generation"
      max_n_programs: 10000
      perform_execution: False

      path_to_documentation: generators/strategies/docs_artifacts/qiskit_std.md
      # seed_program_folder: data/circuit_fragments