# v017: LLM Generation like v016 but with an empty API file

# Changelog
# - Two oracles: equivalence check + QASM Back-Translation

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_oracles_any_circuit_var.jinja
      output_folder: program_bank/v017/
      circuit_generation_strategy: "llm_api_based_generation"
      max_n_programs: 100
      perform_execution: False

      # path_to_documentation: generators/strategies/docs_artifacts/qiskit_std.md
      # seed_program_folder: data/circuit_fragments
      api_file: null