# v023: Random with Equivalence after Optimization oracle

# Changelog
# - from v022
# - support chain oracle
# - skip often erroneous QASM
# - disable every BQSKit exporter
# - add final measurement flag

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_no_code.jinja
      output_folder: program_bank/v023/
      circuit_generation_strategy: "random"
      max_n_qubits: 11
      max_n_gates: 5
      add_final_meas: False

      max_n_programs: 3
      perform_execution: False

      active_oracles:
        - oracle_exporter
        - oracle_optimizer
        - oracle_chain
        - oracle_comparator

      # path_to_documentation: generators/strategies/docs_artifacts/qiskit_std.md
      # seed_program_folder: data/circuit_fragments