# Use the slim Python 3.10 image
FROM python:3.10-slim

ARG UID=1000
ARG GID=1000

RUN groupadd -g $GID regularuser && \
    useradd -m -u $UID -g $GID -s /bin/bash regularuser

# Set environment variable to avoid issues with pip and locales
ENV PYTHONUNBUFFERED=1
ENV LANG=C.UTF-8

# Install Qiskit version 1.2.0
RUN pip install --no-cache-dir qiskit==1.2.1
RUN pip install qiskit-aer==0.15.1 qiskit-ibm-runtime==0.29.1
RUN pip install pytket==1.32.0 pytket-qiskit==0.56.0

# Create and set the working directory
WORKDIR /workspace
# change the owner of the working directory
RUN chown -R regularuser /workspace

# Copy the Python script into the container
COPY to_execute.py /workspace/

USER regularuser

# Set the default command to run the Python script
CMD ["python", "to_execute.py"]
