PATH_ROOT_DIR: ./
DIR_PROGRAM_BANK: program_bank/v003/2024_10_18__10_19__qiskit
INFO_TO_USE_FOR_CLUSTERING:
  - exception_message
  - essential_file_content
PROMPT_CONTENT: BOTH
AI_MODEL: llama-3.1-70b-versatile
N_POSITIVE_EXAMPLES_TO_SHOW_LLM: 5
N_NEGATIVE_EXAMPLES_TO_SHOW_LLM: 0
SAMPLE_SIZE: null
CLUSTERING_METHOD: KMEANS
CACHE_FOLDER: .cache


VECTORIZATION_METHOD: TFIDF
USE_PCA: True