# v002 differs from v001 in:
# it removes the Delay, Measure and Reset gates from the gate set
# it parses with Qiskit using the legacy instructions
# qasm2.loads(qasm, custom_instructions=qasm2.LEGACY_CUSTOM_INSTRUCTIONS)


commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/morphq_w_oracles.jinja
      output_folder: program_bank/v002/
      max_n_qubits: 30
      max_n_gates: 10
      max_n_programs: 10000
      perform_execution: False