# v006: same as v005

# Changelog
# - add support for BQSKit
# - fixed the order of operations in PennyLane export to QASM


commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/morphq_w_oracles.jinja
      output_folder: program_bank/v006/
      max_n_qubits: 32
      max_n_gates: 10
      max_n_programs: 100000
      perform_execution: False