# v013: Test Suite Only

# Changelog
# - add generator that uses only the qasm files extracted from the qiskit test

commands:
  - module: generators.morphq_like_w_oracles
    arguments:
      prompt: generators/scaffold_oracles_any_circuit_var.jinja
      output_folder: program_bank/v013/
      circuit_generation_strategy: "test_suite_only"
      max_n_programs: 10000
      perform_execution: False

      # path_to_documentation: generators/strategies/docs_artifacts/qiskit_std.md
      seed_program_folder: data/circuit_fragments