# v039: Add Qiskit Generator

# Changelog:
# Add Wiskit genreator

batch_size: 100
budget_time_sec: 300


commands:
  - module: qite.generators.qiskit_code_gen
    arguments:
      num_qubits: 11  # BQSKIT LIMITATION: max 10 qubits
      num_gates: 15
      # seed: 42
      only_qregs: True
      final_measure: False
      num_programs: <<BATCH_SIZE>>
      output_dir: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>
    config:
      gate_set: [
        'barrier', 'ccx', 'ccz', 'cp', 'cx', 'crx', 'cry', 'crz', 'cs',
        'csdg', 'cswap', 'csx', 'cu', 'cy', 'cz', 'dcx', 'ecr', 'h', 'id',
        'iswap', 'mcp', 'mcrx', 'mcry', 'mcrz', 'mcx', 'p', 'r', 'rcccx',
        'rccx', 'rv', 'rx', 'rxx', 'ry', 'ryy', 'rz', 'rzx', 'rzz', 's',
        'sdg', 'swap',
      ]

  - module: qite.convert_to_qasm
    arguments:
      input_folder: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>
    config:
      program_id_range: [0, <<BATCH_SIZE>>]
      platforms: [
        'qiskit', 'pytket', 'pennylane',
        # 'bqskit'
      ]

  - module: qite.qite_loop
    arguments:
      input_folder: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>
      number_of_rounds: 6
      n_transform_iter: 1
    config:
      platforms: [
        'qiskit', 'pytket', 'pennylane',
        # 'bqskit'
      ]
      coverage: True
      template_coverage_file: config/template_coverage/qite.cover
      program_id_range: [0, <<BATCH_SIZE>>]

  # - module: qite.spot_divergences
  #   arguments:
  #     input_folder: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>
  #     comparison_folder: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>/comparison
  #     metadata_folder: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>/metadata
  #   config:
  #     program_id_range: [0, <<BATCH_SIZE>>]


  # - module: qite.explore_warnings
  #   arguments:
  #     folder_path: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>/comparison
  #     top_k: 10
  #     target_field: 'equivalence'

  # - module: qite.explore_warnings
  #   arguments:
  #     folder_path: program_bank/<<THIS_FILE_NAME>>/<<RUN_FOLDER>>/error
  #     top_k: 10
  #     target_field: 'error'